/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Business3: typeof import('./src/components/business3/index.vue')['default']
    ControlsDialog: typeof import('./src/components/controls-dialog/controls-dialog.vue')['default']
    ControlsTab: typeof import('./src/components/controls-tab/controls-tab.vue')['default']
    ControlsTabs: typeof import('./src/components/controls-tabs/controls-tabs.vue')['default']
    Dialog: typeof import('./src/components/dialog/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTab: typeof import('element-plus/es')['ElTab']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    HockeyTeamList: typeof import('./src/components/HockeyTeamList.vue')['default']
    HockeyTeamListItem: typeof import('./src/components/HockeyTeamListItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
